### ISSUE TITLE
How to change placement

### ISSUE THREAD

**Issue by awesomekid1021** [manuelpires/nft-collection-generator#1]
So just a question here, is there a way to change the placement of the generated images. For example, my images come out on one side of the screen but I want them to be in the center
![0](https://user-images.githubusercontent.com/33333641/133889678-c200c05b-af1c-4d35-9f25-e55aa06b8e62.png)
.

**Comment by manuelpires** [comment]
Yes there are two ways to do this:
- For merging the images we use the [merge-images](https://www.npmjs.com/package/merge-images) npm package. Right now we only feed it with the images source path but, as described in its README, you can also send the (x, y) coordinates where you want your image to be placed in the final result. The problem with this, is that it would over-complicate the traits configuration. For each option in the configuration, you'd need to add not only the image source path but also the (x, y) coordinates for each image. I didn't implement it because I wanted the configuration to be as simple as possible.
- The other way to solve this issue, is to use images that already have the placement considered into themselves, just as the example images in the `traits` folder. See that all images layers have the same size, and that the "upper" layers have their objects already centred.
